add default grafana dashboard

diff --git a/.github/workflows/install-software.yml b/.github/workflows/install-software.yml
--- a/.github/workflows/install-software.yml
+++ b/.github/workflows/install-software.yml
@@ -39,12 +39,12 @@ jobs:
       - name: Backup previous grafana values
         run: |
           ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@${{ secrets.AWS_EC2_PUBLIC_IP }} \
-            'ls /home/ec2-user/grafana_values.yml && mv /home/ec2-user/grafana_values.yml /home/ec2-user/grafana_values_$(date +\%Y\%m\%d\%H\%M\%S).yml  || echo "File not found, skipping backup"'
+            'ls /home/ec2-user/grafana && mv /home/ec2-user/grafana /home/ec2-user/grafana_$(date +\%Y\%m\%d\%H\%M\%S).yml  || echo "Grafana folder not found, skipping backup"'
 
-      - name: Copy new grafana values to EC2
+      - name: Copy grafana folder to EC2
         run: |
-          mv grafana/values.yml grafana_values.yml
-          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa grafana_values.yml ec2-user@${{ secrets.AWS_EC2_PUBLIC_IP }}:/home/ec2-user/
+          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r ./grafana ec2-user@${{ secrets.AWS_EC2_PUBLIC_IP }}:/home/ec2-user/grafana
+
 
       - name: Run installation script on EC2
         run: |
